# Generated by Django 6.0.4 on 2026-07-02 16:27
# [KUSTOM] FILE BARU (auto-generate): migrasi buat field `created_at` + ordering.
#          Jangan diedit manual; ini yang bikin kolom waktu di database.
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
